import * as fs from 'fs';
import * as path from 'path';

export function prepareGeneratedOutput(outputDir: string): void {
  const generatedRoot = path.resolve(outputDir, 'generated');
  const apiDir = path.join(generatedRoot, 'api');
  const e2eDir = path.join(generatedRoot, 'e2e');

  for (const dir of [apiDir, e2eDir]) {
    if (fs.existsSync(dir)) {
      fs.rmSync(dir, { recursive: true, force: true });
    }
  }
}

export async function writeTestFile(
  outputDir: string,
  type: 'api' | 'e2e',
  fileName: string,
  content: string
): Promise<string> {
  const dir = path.join(outputDir, 'generated', type);
  fs.mkdirSync(dir, { recursive: true });
  const extension = type === 'e2e' ? '.spec.ts' : '.test.ts';
  const filePath = path.join(dir, `${fileName}${extension}`);
  const header = `// Generated by test-forge on ${new Date().toISOString()}\n// Review before committing.\n\n`;
  fs.writeFileSync(filePath, header + content, 'utf-8');
  console.log(`  Written: ${path.relative(process.cwd(), filePath)}`);
  return filePath;
}

export function writeReport(outputDir: string, report: object): string {
  const reportsDir = path.join(outputDir, 'reports');
  fs.mkdirSync(reportsDir, { recursive: true });
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
  const filePath = path.join(reportsDir, `forge-report-${timestamp}.json`);
  fs.writeFileSync(filePath, JSON.stringify(report, null, 2), 'utf-8');
  return filePath;
}
